# Generated by Django 6.0.1 on 2026-02-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_tasks/', verbose_name='Файл с заданием')),
                ('deadline', models.DateTimeField(verbose_name='Крайний срок (Дедлайн)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='ashyk_lms_app.course', verbose_name='Курс')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='ashyk_lms_app.studentgroup', verbose_name='Группа')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homeworks', to='ashyk_lms_app.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_submissions/', verbose_name='Файл с решением')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Сдано'), ('on_review', 'На проверке'), ('graded', 'Оценено')], default='submitted', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('grade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_submission', to='ashyk_lms_app.grade', verbose_name='Оценка в журнале')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ashyk_lms_app.homework', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='ashyk_lms_app.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сдача задания',
                'verbose_name_plural': 'Сдачи заданий',
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
