# Generated by Django 6.0.1 on 2026-01-21 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0002_educationalprogram_remove_user_group_name_curriculum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('grade_type', models.CharField(choices=[('lecture', 'Лекция'), ('homework', 'Үй жұмысы'), ('practice', 'Тәжірибе'), ('lab', 'Зертханалық'), ('srsp', 'СРСП'), ('exam', 'Емтихан')], default='practice', max_length=20, verbose_name='Тип работы')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выставления')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='ashyk_lms_app.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='ashyk_lms_app.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['created_at'],
            },
        ),
    ]
