# Generated by Django 6.0 on 2026-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0002_homework_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_courses', to='ashyk_lms_app.studentgroup', verbose_name='Доступно группам (если пусто — всем)'),
        ),
    ]
