# Generated by Django 6.0 on 2026-02-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0003_course_allowed_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='group',
        ),
        migrations.AddField(
            model_name='homework',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='ashyk_lms_app.studentgroup', verbose_name='Доступно группам (если пусто — никому)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_courses', to='ashyk_lms_app.studentgroup', verbose_name='Доступно группам (если пусто — никому)'),
        ),
    ]
