# Generated by Django 6.0 on 2026-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0004_remove_homework_group_homework_allowed_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='ashyk_lms_app.studentgroup', verbose_name='Доступно группам (если пусто — всем участникам курса)'),
        ),
    ]
