# Generated by Django 6.0.1 on 2026-01-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0004_test_question_testresult_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('retake', 'Пересдача'), ('closed', 'Закрыт')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_tests', to='ashyk_lms_app.student', verbose_name='Студент (индивидуально)'),
        ),
        migrations.AddField(
            model_name='test',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='ashyk_lms_app.studentgroup', verbose_name='Группа'),
        ),
    ]
