# Generated by Django 6.0.1 on 2026-01-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0005_test_status_test_student_test_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='ashyk_lms_app.question', verbose_name='Вопрос')),
                ('selected_variants', models.ManyToManyField(to='ashyk_lms_app.variant', verbose_name='Выбранные варианты')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ashyk_lms_app.student', verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='ashyk_lms_app.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'Ответы студентов',
                'unique_together': {('student', 'test', 'question')},
            },
        ),
    ]
