# Generated by Django 6.0 on 2026-02-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0005_alter_homework_allowed_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Данные расписания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='ashyk_lms_app.studentgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расписание группы',
                'verbose_name_plural': 'Расписания групп',
            },
        ),
    ]
