# Generated by Django 6.0 on 2026-02-09 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0006_groupschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='ashyk_lms_app.course', verbose_name='Курс'),
        ),
    ]
