# Generated by Django 6.0 on 2026-02-09 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0007_grade_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выставления'),
        ),
    ]
