# Generated by Django 6.0.4 on 2026-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0008_alter_grade_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя (username)')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общий балл')),
            ],
            options={
                'verbose_name': 'Итоговый балл',
                'verbose_name_plural': 'Итоговые баллы',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='iframe_content',
            field=models.TextField(blank=True, default='', verbose_name='Iframe контент'),
        ),
    ]
