# Generated by Django 6.0.4 on 2026-04-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0009_studentfinalscore_lecture_iframe_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_presentations/', verbose_name='Файл презентации (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='ashyk_lms_app.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Презентация курса',
                'verbose_name_plural': 'Презентации курсов',
            },
        ),
    ]
