# Generated by Django 6.0.4 on 2026-04-29 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0010_coursepresentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course_images/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ashyk_lms_app.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Фото курса',
                'verbose_name_plural': 'Фото курса',
            },
        ),
        migrations.DeleteModel(
            name='CoursePresentation',
        ),
    ]
