# Generated by Django 6.0.4 on 2026-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0012_courseimage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimage',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Действие (пусто или 'click')"),
        ),
    ]
