# Generated by Django 6.0.4 on 2026-04-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0013_alter_courseimage_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Фото курса', 'verbose_name_plural': 'Фото курса'},
        ),
        migrations.AddField(
            model_name='courseimage',
            name='content_html',
            field=models.TextField(blank=True, null=True, verbose_name='Контент поверх (HTML/текст)'),
        ),
        migrations.AddField(
            model_name='courseimage',
            name='is_lecture_list',
            field=models.BooleanField(default=False, verbose_name='Показывать список лекций поверх'),
        ),
        migrations.AddField(
            model_name='courseimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
