# Generated by Django 6.0.4 on 2026-04-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyk_lms_app', '0014_alter_courseimage_options_courseimage_content_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseimage',
            name='custom_lecture_list',
            field=models.TextField(blank=True, null=True, verbose_name='Свой список лекций (каждая строка — новый пункт)'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='is_lecture_list',
            field=models.BooleanField(default=False, verbose_name='Авто-список лекций курса'),
        ),
    ]
